# Site settings
title: Rajvir Jhawar
description: My person website
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rajvir Jhawar
user_description: I am a software developer hailing from Calgary, Alberta, I have over 4+ years of development experinece.
user_title: Software Developer Extraordinaire 
email: rajvir.jhawar@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
