# Site settings
title: Chitresh Goel
description: Personal Website
# baseurl: "" # the subpath of your site, e.g. /blog
#url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Chitresh Goel
user_description: 
user_title: Competetive Programming and Computer Vision Enthusiast.
email: goelchitresh13@gmail.com
twitter_username: Chitreshg13
github_username:  Chitresh13
#gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']

