# Site settings
title: Kayhan
description: its me baby
baseurl: "kayhanliao" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: KAYHAN EryÄ±lmaz
user_description:
user_title: Data Scientist
email: kayhankubi@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
