# Site settings
title: Gergely Máthé
description: Gergely Máthé's personal website
baseurl: "https://gergelymathe.github.io" # the subpath of your site, e.g. /blog
url: "https://gergelymathe.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Gergely Máthé
user_description: "Have more than 9 years of experience in computational problem-solving ranging from academia to the financial industry. Machine Learning quantitative developer and PhD candidate in the field of computational astrophysics (planed finishing: Aug. of 2025.)"
user_title: AI/ML-developer/-researcher | computational physicist | PhD candidate in computational astrophysics
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: gergelymathe
github_username: gergelymathe
googleScholar_username: citations?user=HZGByQ8AAAAJ&hl=en
email: gergely.mathe07@gmail.com
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
